export const dummySales = [
  {
    id: 1,
    createds: "2023-10-01",
    category: [{ name: "Electronics" }],
    brand: "Apple",
    product: "iPhone 14",
    quantity: 10,
    price: 999.99,
    price_total: 9999.9,
  },
  {
    id: 2,
    createds: "2023-10-02",
    category: [{ name: "Electronics" }],
    brand: "Samsung",
    product: "Galaxy S22",
    quantity: 5,
    price: 799.99,
    price_total: 3999.95,
  },
  {
    id: 3,
    createds: "2023-10-03",
    category: [{ name: "Home Appliances" }],
    brand: "LG",
    product: "Refrigerator",
    quantity: 2,
    price: 1200.0,
    price_total: 2400.0,
  },
  {
    id: 4,
    createds: "2023-10-04",
    category: [{ name: "Home Appliances" }],
    brand: "Whirlpool",
    product: "Washing Machine",
    quantity: 3,
    price: 600.0,
    price_total: 1800.0,
  },
  {
    id: 5,
    createds: "2023-10-05",
    category: [{ name: "Electronics" }],
    brand: "Sony",
    product: "PlayStation 5",
    quantity: 7,
    price: 499.99,
    price_total: 3499.93,
  },
  {
    id: 6,
    createds: "2023-10-06",
    category: [{ name: "Furniture" }],
    brand: "IKEA",
    product: "Sofa",
    quantity: 4,
    price: 300.0,
    price_total: 1200.0,
  },
  {
    id: 7,
    createds: "2023-10-07",
    category: [{ name: "Electronics" }],
    brand: "Dell",
    product: "Laptop",
    quantity: 6,
    price: 899.99,
    price_total: 5399.94,
  },
  {
    id: 8,
    createds: "2023-10-08",
    category: [{ name: "Electronics" }],
    brand: "HP",
    product: "Printer",
    quantity: 8,
    price: 150.0,
    price_total: 1200.0,
  },
  {
    id: 9,
    createds: "2023-10-09",
    category: [{ name: "Home Appliances" }],
    brand: "Bosch",
    product: "Dishwasher",
    quantity: 1,
    price: 800.0,
    price_total: 800.0,
  },
  {
    id: 10,
    createds: "2023-10-10",
    category: [{ name: "Electronics" }],
    brand: "Nikon",
    product: "Camera",
    quantity: 3,
    price: 1200.0,
    price_total: 3600.0,
  },
  {
    id: 11,
    createds: "2023-10-11",
    category: [{ name: "Furniture" }],
    brand: "Ashley",
    product: "Dining Table",
    quantity: 2,
    price: 500.0,
    price_total: 1000.0,
  },
  {
    id: 12,
    createds: "2023-10-12",
    category: [{ name: "Electronics" }],
    brand: "Bose",
    product: "Headphones",
    quantity: 15,
    price: 299.99,
    price_total: 4498.85,
  },
  {
    id: 13,
    createds: "2023-10-13",
    category: [{ name: "Home Appliances" }],
    brand: "KitchenAid",
    product: "Mixer",
    quantity: 5,
    price: 199.99,
    price_total: 999.95,
  },
  {
    id: 14,
    createds: "2023-10-14",
    category: [{ name: "Electronics" }],
    brand: "Microsoft",
    product: "Surface Pro",
    quantity: 4,
    price: 899.99,
    price_total: 3599,
  },
];

export const dummyProducts = [
  {
    id: 1,
    category: "Electronics",
    brand: "Apple",
    name: "iPhone 14",
    stock: 50,
  },
  {
    id: 2,
    category: "Electronics",
    brand: "Samsung",
    name: "Galaxy S22",
    stock: 30,
  },
  {
    id: 3,
    category: "Home Appliances",
    brand: "LG",
    name: "Refrigerator",
    stock: 15,
  },
  {
    id: 4,
    category: "Home Appliances",
    brand: "Whirlpool",
    name: "Washing Machine",
    stock: 20,
  },
  {
    id: 5,
    category: "Electronics",
    brand: "Sony",
    name: "PlayStation 5",
    stock: 25,
  },
  {
    id: 6,
    category: "Furniture",
    brand: "IKEA",
    name: "Sofa",
    stock: 10,
  },
  {
    id: 7,
    category: "Electronics",
    brand: "Dell",
    name: "Laptop",
    stock: 40,
  },
  {
    id: 8,
    category: "Electronics",
    brand: "HP",
    name: "Printer",
    stock: 35,
  },
  {
    id: 9,
    category: "Home Appliances",
    brand: "Bosch",
    name: "Dishwasher",
    stock: 5,
  },
  {
    id: 10,
    category: "Electronics",
    brand: "Nikon",
    name: "Camera",
    stock: 12,
  },
  {
    id: 11,
    category: "Furniture",
    brand: "Ashley",
    name: "Dining Table",
    stock: 8,
  },
  {
    id: 12,
    category: "Electronics",
    brand: "Bose",
    name: "Headphones",
    stock: 60,
  },
  {
    id: 13,
    category: "Home Appliances",
    brand: "KitchenAid",
    name: "Mixer",
    stock: 18,
  },
  {
    id: 14,
    category: "Electronics",
    brand: "Microsoft",
    name: "Surface Pro",
    stock: 22,
  },
  {
    id: 15,
    category: "Furniture",
    brand: "Wayfair",
    name: "Bookshelf",
    stock: 14,
  },
  {
    id: 16,
    category: "Electronics",
    brand: "Fitbit",
    name: "Smartwatch",
    stock: 45,
  },
  {
    id: 17,
    category: "Home Appliances",
    brand: "Dyson",
    name: "Vacuum Cleaner",
    stock: 9,
  },
  {
    id: 18,
    category: "Electronics",
    brand: "Logitech",
    name: "Wireless Mouse",
    stock: 50,
  },
  {
    id: 19,
    category: "Furniture",
    brand: "Herman Miller",
    name: "Office Chair",
    stock: 7,
  },
  {
    id: 20,
    category: "Home Appliances",
    brand: "Samsung",
    name: "Air Conditioner",
    stock: 3,
  },
  {
    id: 21,
    category: "Electronics",
    brand: "Canon",
    name: "Camcorder",
    stock: 11,
  },
  {
    id: 22,
    category: "Furniture",
    brand: "West Elm",
    name: "Coffee Table",
    stock: 6,
  },
  {
    id: 23,
    category: "Electronics",
    brand: "Razer",
    name: "Gaming Laptop",
    stock: 4,
  },
  {
    id: 24,
    category: "Home Appliances",
    brand: "Frigidaire",
    name: "Microwave",
    stock: 20,
  },
  {
    id: 25,
    category: "Electronics",
    brand: "Asus",
    name: "Gaming Monitor",
    stock: 15,
  },
];

export const dummyPurchase = [
  {
    id: 1,
    createds: "2023-10-01",
    category: [{ name: "Electronics" }],
    firm: "TechCorp",
    brand: "Apple",
    product: "iPhone 14",
    quantity: 10,
    price: 999.99,
    price_total: 9999.9,
  },
  {
    id: 2,
    createds: "2023-10-02",
    category: [{ name: "Electronics" }],
    firm: "GadgetWorld",
    brand: "Samsung",
    product: "Galaxy S22",
    quantity: 5,
    price: 799.99,
    price_total: 3999.95,
  },
  {
    id: 3,
    createds: "2023-10-03",
    category: [{ name: "Home Appliances" }],
    firm: "HomeGoods",
    brand: "LG",
    product: "Refrigerator",
    quantity: 2,
    price: 1200.0,
    price_total: 2400.0,
  },
  {
    id: 4,
    createds: "2023-10-04",
    category: [{ name: "Home Appliances" }],
    firm: "ApplianceCo",
    brand: "Whirlpool",
    product: "Washing Machine",
    quantity: 3,
    price: 600.0,
    price_total: 1800.0,
  },
  {
    id: 5,
    createds: "2023-10-05",
    category: [{ name: "Electronics" }],
    firm: "GameZone",
    brand: "Sony",
    product: "PlayStation 5",
    quantity: 7,
    price: 499.99,
    price_total: 3499.93,
  },
  {
    id: 6,
    createds: "2023-10-06",
    category: [{ name: "Furniture" }],
    firm: "IKEA",
    brand: "IKEA",
    product: "Sofa",
    quantity: 4,
    price: 300.0,
    price_total: 1200.0,
  },
  {
    id: 7,
    createds: "2023-10-07",
    category: [{ name: "Electronics" }],
    firm: "Techies",
    brand: "Dell",
    product: "Laptop",
    quantity: 6,
    price: 899.99,
    price_total: 5399.94,
  },
  {
    id: 8,
    createds: "2023-10-08",
    category: [{ name: "Electronics" }],
    firm: "Office Supplies",
    brand: "HP",
    product: "Printer",
    quantity: 8,
    price: 150.0,
    price_total: 1200.0,
  },
  {
    id: 9,
    createds: "2023-10-09",
    category: [{ name: "Home Appliances" }],
    firm: "CleanHome",
    brand: "Bosch",
    product: "Dishwasher",
    quantity: 1,
    price: 800.0,
    price_total: 800.0,
  },
  {
    id: 10,
    createds: "2023-10-10",
    category: [{ name: "Electronics" }],
    firm: "PhotoPro",
    brand: "Nikon",
    product: "Camera",
    quantity: 3,
    price: 1200.0,
    price_total: 3600.0,
  },
  {
    id: 11,
    createds: "2023-10-11",
    category: [{ name: "Furniture" }],
    firm: "HomeStyle",
    brand: "Ashley",
    product: "Dining Table",
    quantity: 2,
    price: 500.0,
    price_total: 1000.0,
  },
  {
    id: 12,
    createds: "2023-10-12",
    category: [{ name: "Electronics" }],
    firm: "AudioHub",
    brand: "Bose",
    product: "Headphones",
    quantity: 15,
    price: 299.99,
    price_total: 4498.85,
  },
];
