import Head from "next/head";
import { Box, Typography } from "@mui/material";
import DashboardCards from "@/components/DashboardCards";
import Charts from "@/components/Charts";
import { getSession } from "next-auth/react";
import { useEffect } from "react";
import useStockCalls from "@/hooks/useStockCalls";

export default function Home() {
  const { getTransactions, getCategories, getBrands, getProducts } =
    useStockCalls();
  useEffect(() => {
    getProducts();
    getTransactions();
    getCategories();
    getBrands();
  }, []);

  return (
    <>
      <Head>
        <title>CapTracker</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box>
        <Typography
          variant="h4"
          color="error"
          mb={2}
          sx={{
            fontWeight: "bold",
            textTransform: "uppercase",
          }}
        >
          Dashboard
        </Typography>
        <DashboardCards />
        <Charts />
      </Box>
    </>
  );
}
export const getServerSideProps = async (context) => {
  const session = await getSession(context);
  if (!session) {
    return {
      redirect: {
        destination: "/auth/login",
        permanent: false,
      },
    };
  }

  return {
    props: { session },
  };
};
